### PR TITLE
"Wolfbrain" probably doesn't make sense for the GH token. What does?

### PR DESCRIPTION
**Pull request by iamvery**
- [ ] update nerdbot and environment variable

### CODE REVIEW

**Comment by stevenharman** [comment]
Perhaps a requirement is for folks to set up a GitHub account just for their bot? That would also allow them to better control access.

**Comment by stevenharman** [comment]
Oh... wait. I see. Never mind. :+1:

**Comment by johnallen3d** [comment]
Any plans to merge this? I'm setting up this handler and wasn't sure what this environment variable meant. Also, it would be good to list what permissions are required.

Thanks for the plugin!

**Comment by iamvery** [comment]
@johnallen3d thanks for calling me out on this! Yes this needs to be finished. Actually, revisiting it should probably be a handler configuration (which may be set by ENV in `lita_config.rb`). I might have some time today. Would love to get it in there for you :smile:

**Comment by wolfbrain** [comment]
:eyes: @

**Comment by iamvery** [comment]
Just pushed a better implementation of this that uses Lita's handler configuration. Will test, merge, and issue a new release if all looks well :+1:

**Comment by wolfbrain** [comment]
:eyes: @mutexkid

**Comment by iamvery** [comment]
@johnallen3d just published [v0.3.0](https://github.com/iamvery/lita-reviewme/pull/4). It should work better for you :). Let me know if you have any other ideas to make things better!

**Comment by johnallen3d** [comment]
Excellent, thanks!

**Pull request merged**
