### PR TITLE
Add review groups

### PR DESCRIPTION
**Pull request by KyFaSt**
* Anyone can create a review group
* Anyone can be added or removed from any review group
* Should there be a bulk-remove option?
* Should this be a plugin per room instead somehow? how to even do that?
* Should there be a way to find out what groups a reviewer is included in?

### CODE REVIEW

**Comment by gschorkopf** [comment]
This isn't really important, but I found it interesting that GitHub organized your commits like this:

screen shot 2015-09-29 at 10 09 00 am

**Comment by gschorkopf** [comment]
Looks solid! I think we should consider strengthening phrasing in a few spot places. Otherwise, great work!

**Comment by KyFaSt** [comment]
any thoughts @iamvery?

**Comment by iamvery** [comment]
This looks good! Were you ever able to figuring anything out for channel-specific review rotations? I haven't been able to really sit down and think about the pros/cons of that, but I tend to like the idea. What do you think?

**Comment by iamvery** [comment]
OoOo check out #34, it might be awesome!

**Comment by iamvery** [comment]
see #34

**Comment by KyFaSt** [comment]
pour one out for pr #33

**Comment by iamvery** [comment]
:put_litter_in_its_place:

**Comment by gschorkopf** [comment]
:musical_note:  "I don't wanna close my eyes... I don't wanna faaaaall asleep..." :musical_note:

**Pull request closed without merging**
