### PR TITLE
Add review groups

### PR DESCRIPTION
**Pull request by iamvery**
e.g. Backend, iOS, or Project_Name reviews

### CODE REVIEW

**Comment by killpack** [comment]
Suggestion: `lita: backend reviewers` to just see reviewers for the `backend` group.

**Comment by iamvery** [comment]
Nice one. I actually talked myself out of that, but I can see it being useful.

**Comment by killpack** [comment]
Seems like most of the time you probably wouldn't care about who's a reviewer in another department, is all.

**Comment by stevenharman** [comment]
The language feels wonky to me. `lita: review me <channel|group> url` seems more obvious. And consistent with the other commands.

**Comment by gschorkopf** [comment]
What would we need to make this work? This is using redis, right? Can we have a key value store of teams and users (array) as:

```
{ "backend" => ["githubuser1"] }
```

**Comment by iamvery** [comment]
Yes, using redis. I looked into this a little bit. I believe I was leaning towards using a namespace for groups rather than a hash structure. It could work either way, but I don't think you have access to the methods currently used for "rotation" on hash values. Might be wrong..

**Comment by iamvery** [comment]
Maybe #34 is awesome sauce?

**Comment by iamvery** [comment]
see #34

**Pull request closed without merging**
